#!/bin/sh

# get the most recent tag, for example "1.8.7":
TAG=$(git describe --tags --abbrev=0)
# Make a tarball
git archive -v -o ibus-table-chinese-${TAG}.tar.gz --prefix=ibus-table-chinese-${TAG}/ ${TAG}